apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deploy
  labels:
    app: green-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: green-app
  template:
    metadata:
      labels:
        app: green-app
    spec:
      containers:
      - name: green-app
        image: nginx:1.14.2
        ports: 80
        - containerPort: 80
